# Build stage
FROM node:18-slim

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

WORKDIR /app

COPY package.json package-lock.json ./

RUN sed -i \
    -e 's|https://artifactory.boschdevcloud.com/artifactory/api/npm/cs-npmjs-remote/||g' \
    package-lock.json

RUN npm ci --legacy-peer-deps --no-audit

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY . .

EXPOSE 4200

ENTRYPOINT ["/entrypoint.sh"]
